const BRANDS = [
  { id: 'lifewave', name: 'LifeWave', tag: 'Fotobioterapia', tagColor: '#6d28d9', tagBg: '#ede9fe', bg1: 'linear-gradient(135deg,#3b0764,#6d28d9)', bg2: 'linear-gradient(135deg,#4c1d95,#7c3aed)' },
  { id: 'neuro', name: 'Neuro', tag: 'Nootrópicos', tagColor: '#065f46', tagBg: '#d1fae5', bg1: 'linear-gradient(135deg,#064e3b,#065f46)', bg2: 'linear-gradient(135deg,#065f46,#10b981)' },
  { id: 'analemma', name: 'Analemma', tag: 'Agua estructurada', tagColor: '#0369a1', tagBg: '#e0f2fe', bg1: 'linear-gradient(135deg,#0c4a6e,#0369a1)', bg2: 'linear-gradient(135deg,#075985,#38bdf8)' },
  { id: 'gamma-light', name: 'Gamma Light', tag: 'Luz gamma', tagColor: '#92400e', tagBg: '#fef3c7', bg1: 'linear-gradient(135deg,#78350f,#92400e)', bg2: 'linear-gradient(135deg,#92400e,#f59e0b)' },
  { id: 'ess60', name: 'ESS60', tag: 'Carbono C60', tagColor: '#9d174d', tagBg: '#fce7f3', bg1: 'linear-gradient(135deg,#831843,#9d174d)', bg2: 'linear-gradient(135deg,#9d174d,#ec4899)' },
  { id: 'h2', name: 'H2 Tablets', tag: 'Hidrógeno', tagColor: '#0369a1', tagBg: '#e0f2fe', bg1: 'linear-gradient(135deg,#0c4a6e,#0369a1)', bg2: 'linear-gradient(135deg,#075985,#38bdf8)' },
];

const KITS = [
  { id: 'longevidad', name: 'Kit Longevidad', products: 'X39 · Glutathione · ESS60', link: '#' },
  { id: 'cerebro', name: 'Kit Cerebro', products: 'Gamma 40Hz · Neuro · Calm & Clarity', link: '#' },
  { id: 'sueno', name: 'Kit Sueño', products: 'Silent Nights · Sleep & Recharge', link: '#' },
  { id: 'deportista', name: 'Kit Deportista', products: 'X49 · Energy Enhancer · H2 Tablets', link: '#' },
  { id: 'antistres', name: 'Kit Anti-estrés', products: 'Aeon · Calm & Clarity · IceWave', link: '#' },
];

const PRODUCTS = [
  // LIFEWAVE
  { brand: 'lifewave', name: 'X39', badge: 'Más vendido', badgeBg: '#e5d4f1', badgeColor: '#6d28d9', price: '$235.000', priceDay: '$7.833/día', stock: '30 parches', stockCount: 27, stockStatus: 'Entregas en 24hs', img: 'img/productos/lifewave/x39.png', goals: ['longevidad', 'energia', 'inmunidad'], desc: 'Activa las células madre propias. Regeneración celular profunda.', variants: [{ name: '10 parches', price: '$82.250', stock: '27' }, { name: '30 parches', price: '$235.000', stock: '27' }] },
  { brand: 'lifewave', name: 'X49', badge: 'En stock', badgeBg: '#e5d4f1', badgeColor: '#6d28d9', price: '$220.000', priceDay: '$7.333/día', stock: '30 parches', stockCount: 15, stockStatus: 'Entregas en 24hs', img: 'img/productos/lifewave/x49.png', goals: ['rendimiento', 'energia'], desc: 'Aumentá tu fuerza, resistencia y masa muscular.', variants: [{ name: '10 parches', price: '$77.000', stock: '15' }, { name: '30 parches', price: '$220.000', stock: '15' }] },
  { brand: 'lifewave', name: 'IceWave', badge: 'Dolor', badgeBg: '#d4e8f1', badgeColor: '#0369a1', price: '$165.000', priceDay: '$5.5/día', stock: '30 parches', stockCount: 10, stockStatus: 'Entregas en 24hs', img: 'img/productos/lifewave/icewave.png', goals: ['dolor'], desc: 'Alivio rápido y sostenido del dolor sin medicamentos.', variants: [{ name: '10 parches', price: '$57.750', stock: '10' }, { name: '30 parches', price: '$165.000', stock: '10' }] },
  { brand: 'lifewave', name: 'Silent Night', badge: 'Sueño', badgeBg: '#e5e0f1', badgeColor: '#6b21a8', price: '$150.000', priceDay: '$5.000/día', stock: '30 parches', stockCount: 15, stockStatus: 'Entregas en 24hs', img: 'img/productos/lifewave/silent%20night.png', goals: ['sueno'], desc: 'Conciliá el sueño más rápido y despertate renovado.', variants: [{ name: '10 parches', price: '$52.500', stock: '15' }, { name: '30 parches', price: '$150.000', stock: '15' }] },
  { brand: 'lifewave', name: 'AEON', badge: 'Calma', badgeBg: '#f0e8f1', badgeColor: '#7c3aed', price: '$150.000', priceDay: '$5.000/día', stock: '30 parches', stockCount: 12, stockStatus: 'Entregas en 24hs', img: 'img/productos/lifewave/AEON 2.png', goals: ['longevidad', 'inmunidad'], desc: 'Reducí el estrés, mejoró tu claridad mental.', variants: [{ name: '10 parches', price: '$52.500', stock: '12' }, { name: '30 parches', price: '$150.000', stock: '12' }] },
  { brand: 'lifewave', name: 'Glutathione', badge: 'Inmunidad', badgeBg: '#d4f1e0', badgeColor: '#0369a1', price: '$150.000', priceDay: '$5.000/día', stock: '30 parches', stockCount: 5, stockStatus: 'Últimas 5 unidades', img: 'img/productos/lifewave/glutathione.png', goals: ['inmunidad', 'longevidad'], desc: 'Elevá el antioxidante maestro de tu cuerpo hasta un 300%.', variants: [{ name: '10 parches', price: '$52.500', stock: '5' }, { name: '30 parches', price: '$150.000', stock: '5' }] },
  { brand: 'lifewave', name: 'Carnosine', badge: 'Anti-aging', badgeBg: '#f1e0d4', badgeColor: '#92400e', price: '$140.400', priceDay: '$4.680/día', stock: '30 parches', stockCount: 8, stockStatus: 'Entregas en 24hs', img: 'img/productos/lifewave/carnosine.png', goals: ['longevidad', 'rendimiento'], desc: 'Regenerá tejidos musculares y articulares.', variants: [{ name: '10 parches', price: '$49.140', stock: '8' }, { name: '30 parches', price: '$140.400', stock: '8' }] },
  { brand: 'lifewave', name: 'SP6 Complete', badge: 'Metabolismo', badgeBg: '#e0f1d4', badgeColor: '#15803d', price: '$160.000', priceDay: '$5.333/día', stock: '30 parches', stockCount: 3, stockStatus: 'Últimas 3 unidades', img: 'img/productos/lifewave/sp6.png', goals: ['energia'], desc: 'Regulá tu apetito y equilibrá tu metabolismo.', variants: [{ name: '10 parches', price: '$56.000', stock: '3' }, { name: '30 parches', price: '$160.000', stock: '3' }] },
  { brand: 'lifewave', name: 'Energy Enhancer', badge: 'Energía', badgeBg: '#d4e0f1', badgeColor: '#0369a1', price: '$150.000', priceDay: '$5.000/día', stock: '30 parches', stockCount: 5, stockStatus: 'Últimas 5 unidades', img: 'img/productos/lifewave/ee.png', goals: ['energia', 'rendimiento'], desc: 'Generá energía sostenida sin cafeína ni estimulantes.', variants: [{ name: '10 parches', price: '$52.500', stock: '5' }, { name: '30 parches', price: '$150.000', stock: '5' }] },

  // NEURO
  { brand: 'neuro', name: 'Neuro Gum: Focus', badge: 'Foco', badgeBg: '#d1fae5', badgeColor: '#065f46', price: '$18.000', priceDay: '$600/día', stock: '1 blister (9 chicles)', stockCount: 22, stockStatus: 'Entregas en 24hs', img: 'img/productos/neuro/neurogum.png', goals: ['foco'], desc: 'Nootrópicos en formato goma para máximo foco mental.', variants: [{ name: '1 Blister', price: '$18.000', stock: '22' }, { name: 'Caja 6 blisters', price: '$85.000', stock: '3' }] },
  { brand: 'neuro', name: 'Sleep & Recharge Mints', badge: 'Sueño', badgeBg: '#d1fae5', badgeColor: '#065f46', price: '$18.000', priceDay: '$600/día', stock: '1 blister (12 mentas)', stockCount: 14, stockStatus: 'Entregas en 24hs', img: 'img/productos/neuro/neurogum.png', goals: ['sueno'], desc: 'Mentas nootrópicas para sueño reparador y profundo.', variants: [{ name: '1 Blister', price: '$18.000', stock: '14' }, { name: 'Caja 6 blisters', price: '$85.000', stock: '2' }] },
  { brand: 'neuro', name: 'Neuro Energy & Focus Mints', badge: 'Energía', badgeBg: '#d1fae5', badgeColor: '#065f46', price: '$15.300', priceDay: '$510/día', stock: '1 lata (12 mentas)', stockCount: 30, stockStatus: 'Entregas en 24hs', img: 'img/productos/neuro/neurogum.png', goals: ['energia', 'foco'], desc: 'Mentas nootrópicas para energía instantánea y claridad mental.', variants: [{ name: '1 Lata', price: '$15.300', stock: '30' }, { name: 'Pack 6 latas', price: '$80.000', stock: '5' }] },
  { brand: 'neuro', name: 'Extra Strength Neuro Energy Gum', badge: 'Potencia', badgeBg: '#d1fae5', badgeColor: '#065f46', price: '$19.550', priceDay: '$651/día', stock: '1 caja (6 blisters)', stockCount: 12, stockStatus: 'Entregas en 24hs', img: 'img/productos/neuro/neurogum.png', goals: ['energia', 'rendimiento'], desc: '100mg cafeína natural para máxima potencia mental y energía.', variants: [{ name: '1 Caja', price: '$19.550', stock: '12' }, { name: 'Pack 3 cajas', price: '$55.000', stock: '4' }] },
  { brand: 'neuro', name: 'Calm & Clarity Mints', badge: 'Calma', badgeBg: '#d1fae5', badgeColor: '#065f46', price: '$15.300', priceDay: '$510/día', stock: '1 blister (12 mentas)', stockCount: 5, stockStatus: 'Últimas 5 unidades', img: 'img/productos/neuro/neurogum.png', goals: ['foco', 'longevidad'], desc: 'Mentas para calma mental y claridad cognitiva con GABA+L-Teanina.', variants: [{ name: '1 Blister', price: '$15.300', stock: '5' }, { name: 'Caja 6 blisters', price: '$75.000', stock: '1' }] },

  // ANALEMMA
  { brand: 'analemma', name: 'Analemma Water Wand', badge: 'Hidratación', badgeBg: '#e0f2fe', badgeColor: '#0369a1', price: '$352.800', priceDay: '$11.760/día', stock: '1 varilla estructuradora', stockCount: 4, stockStatus: 'Últimas 4 unidades', img: 'img/productos/analemma.png', goals: ['energia', 'inmunidad'], desc: 'Agua estructurada para hidratación celular profunda y vitalidad.' },

  // GAMMA LIGHT (CORREGIDO: $200.000, no $1.200.000)
  { brand: 'gamma-light', name: 'Gamma Clarity 40 Hz Light', badge: 'Luz 40Hz', badgeBg: '#fef3c7', badgeColor: '#92400e', price: '$200.000', priceDay: '$6.666/día', stock: '1 dispositivo', stockCount: 15, stockStatus: 'Entregas en 24hs', img: 'img/productos/gamma%20light.png', goals: ['foco', 'longevidad'], desc: 'Estimulación de luz gamma 40Hz para memoria, enfoque y desintoxicación neurológica.' },

  // ESS60
  { brand: 'ess60', name: 'ESS60 en Aceite de Oliva', badge: 'Antioxidante', badgeBg: '#fce7f3', badgeColor: '#9d174d', price: '$187.200', priceDay: '$6.240/día', stock: '50ml', stockCount: 3, stockStatus: 'Últimas 3 unidades', img: 'img/productos/ess60.png', goals: ['longevidad', 'inmunidad'], desc: 'Carbono C60 en aceite de oliva virgen extra puro. 40% OFF en envase especial.' },

  // H2 TABLETS
  { brand: 'h2', name: 'H2 Tablets', badge: 'H₂ Molecular', badgeBg: '#e0f2fe', badgeColor: '#0369a1', price: '$170.000', priceDay: '$5.666/día', stock: '1 frasco (30 tablets)', stockCount: 6, stockStatus: 'Últimas 6 unidades', img: 'img/productos/h2-tablets.png', goals: ['energia', 'inmunidad', 'longevidad'], desc: 'Hidrógeno molecular con +2000 estudios científicos. Máximo antioxidante selectivo.' },

  // STICKERS SHUNGITA
  { brand: 'lifewave', name: 'Stickers Shungita', badge: 'Protección EMF', badgeBg: '#f1d4e8', badgeColor: '#9d174d', price: '$13.685', priceDay: '$456/día', stock: '1 pack (38 stickers)', stockCount: 38, stockStatus: 'Entregas en 24hs', img: 'img/productos/shungita-stickers.png', goals: ['inmunidad'], desc: 'Protección natural contra radiación electromagnética. Stickers anti-radiación.' },
];
