/* Fuente única de los papers BASE (de marca). Lo leen estudios.html y el landing.
   Los papers de OPTIMIZE viven en papers-extra.json (se suman aparte). */
window.STUDIES_BASE = [
  {id:'lw-01',titulo_es:"Caracterización del efecto de la energía emitida por los parches LifeWave sobre el ADN humano",temas:["campos-em","quantum"],brand:'lifewave',type:'vitro',portada:'img/papers/x39-stem-cell-study.jpg',
   title:'Characterizing the Effect of Energy Emitted by LifeWave Patches on Human DNA',
   cite:'Rein G. · Quantum Biology Research Lab · Ridgway, CO · 2012',
   n:'N=1 / 3 réplicas',loc:'Colorado, EE.UU.',dur:'—',
   method:'Estudio in vitro: ADN humano en tubos de vidrio colocados sobre el parche en punto de acupuntura P8. Medición de frecuencias de resonancia y conductividad eléctrica bajo distintas condiciones. No cegado. Financiado por LifeWave ($10,000 USD).',
   results:['Bajo frecuencias de resonancia específicas, X39, Energy Enhancer y SP6 aumentaron la conductividad eléctrica del ADN (p < 0.05)','Mayor efecto en parche Aeon a 39.8 kHz (p = 0.049) y 79.4 kHz (p = 0.030)','Estudio exploratorio de mecanismo básico; N muy pequeño, sin cegamiento'],
   pdf:'estudios/lifewave/x39-stem-cell-study.pdf',doi:'',note:'Financiado por el fabricante. Sin cegamiento ni grupo control adecuado.'},
  {id:'lw-02',titulo_es:"Estudio aleatorizado controlado con placebo sobre los efectos de IceWave® en la reducción del dolor",temas:["dolor"],brand:'lifewave',type:'rct',portada:'img/papers/icewave-pain-double-blind.jpg',
   title:'A Placebo-Controlled Randomized Study on the Effects of IceWave® on Pain Reduction',
   cite:'Budzynski TH, Tang Y, Kan PW, Rider MS · LifeWave Inc. · 2012',
   n:'N=105 (54+51)',loc:'Lake Placid NY + Lakeside AZ',dur:'7 días',
   method:'RCT doble ciego controlado con placebo. Adultos 18–80 años con dolor musculoesquelético EVA ≥ 3. Parches activos o placebo 12 h/día durante 7 días. EVA evaluada en Día 1 y Día 7. Análisis por intención de tratar.',
   results:['Tratamiento −57% dolor Día 1 vs placebo −34% (p < 0.0001)','Tratamiento −43% dolor Día 7 vs placebo −13% (p < 0.0001)','Mayor efecto en los primeros días; sugiere mecanismo de acción rápido'],
   pdf:'estudios/lifewave/icewave-pain-double-blind.pdf',doi:'',note:'Mayor ensayo clínico controlado de LifeWave. Financiado por el fabricante.'},
  {id:'lw-03',titulo_es:"Estudio abierto de dolor que compara IceWave® con distintos analgésicos",temas:["dolor"],brand:'lifewave',type:'piloto',portada:'img/papers/icewave-pain-comparison.jpg',
   title:'Open-label Pain Study Comparing IceWave® to Various Pain Medications',
   cite:'Nazeran H, Rowe G, Clark D · 2013',
   n:'N=35',loc:'EE.UU.',dur:'30 días',
   method:'Estudio abierto comparativo. Pacientes con dolor crónico tratados con IceWave vs grupo de referencia con AINEs u opioides. EVA y calidad de vida a los 0, 15 y 30 días.',
   results:['IceWave produjo reducción de dolor comparable a analgésicos de venta libre','Perfil de efectos adversos favorable vs medicación farmacológica','Mejoras en movilidad y calidad de vida auto-reportada'],
   pdf:'estudios/lifewave/icewave-pain-comparison.pdf',doi:'',note:''},
  {id:'lw-04',titulo_es:"Estudio clínico piloto en humanos — parche de glutatión de LifeWave",temas:["antioxidantes"],brand:'lifewave',type:'piloto',portada:'img/papers/glutathione-pilot-study.jpg',
   title:'Human Clinical Pilot Study — LifeWave Glutathione Patch',
   cite:'Tully L · Energy Medicine Research Institute · 2010',
   n:'N=20',loc:'EE.UU.',dur:'7 días',
   method:'Estudio piloto abierto sin aleatorización. Medición de glutatión intracelular (GSH) por análisis de sangre antes y después del uso del parche.',
   results:['Aumento de glutatión intracelular en el grupo activo','Sin cambios comparables en el grupo control','Requiere confirmación con diseño RCT de mayor N'],
   pdf:'estudios/lifewave/glutathione-pilot-study.pdf',doi:'',note:''},
  {id:'lw-05',titulo_es:"Efectos de los parches Silent Nights® de LifeWave sobre la calidad del sueño",temas:["sueno"],brand:'lifewave',type:'piloto',portada:'img/papers/silent-nights-sleep.jpg',
   title:'The Effects of LifeWave Silent Nights® Patches on Sleep Quality',
   cite:'Shealy CN, Mueller RG · Shealy Wellness Center · Fair Grove, MO · 2011',
   n:'N=25 (insomnio)',loc:'Fair Grove, Missouri',dur:'30 días',
   method:'Estudio abierto sin grupo control. Insomnio diagnosticado. PSQI, Leeds Sleep Evaluation y Epworth Sleepiness Scale. Parche en CV8, 30 min antes de dormir, 30 noches.',
   results:['88% reportó mejoría en duración del sueño','80% mejoró calidad subjetiva (PSQI)','72% alcanzó somnolencia diurna normal (Epworth ≤ 10)'],
   pdf:'estudios/lifewave/silent-nights-sleep.pdf',doi:'',note:''},
  {id:'lw-06',titulo_es:"Tratamiento del insomnio mediante la activación energética de puntos de acupuntura — RCT doble ciego",temas:["sueno"],brand:'lifewave',type:'rct',portada:'img/papers/silent-nights-insomnia-rct.jpg',
   title:'Treatment of Insomnia with Energetic Acupuncture Point Activation — Double-Blind RCT',
   cite:'Shealy CN · Shealy Wellness Center · 2012',
   n:'N=40 (insomnio)',loc:'Fair Grove, Missouri',dur:'30 días',
   method:'RCT doble ciego con placebo. Insomnio según criterios DSM. Asignación 1:1. Desenlace primario PSQI. Análisis por intención de tratar.',
   results:['Mejora significativa en PSQI total vs placebo (p < 0.01)','Reducción del tiempo de latencia del sueño de 45 a 22 min','Sin efectos adversos en ningún grupo'],
   pdf:'estudios/lifewave/silent-nights-insomnia-rct.pdf',doi:'',note:''},
  {id:'lw-07',titulo_es:"Análisis de la variabilidad de la frecuencia cardíaca con los parches Aeon de LifeWave",temas:["sueno"],brand:'lifewave',type:'piloto',portada:'img/papers/aeon-heart-rate-variability.jpg',
   title:'Heart Rate Variability Analysis for LifeWave Aeon Patches',
   cite:'Budzynski TH, Budzynski H, Tang Y · 2010',
   n:'N=20 adultos sanos',loc:'EE.UU.',dur:'Sesión única',
   method:'Análisis espectral de VFC (HF, LF, ratio LF/HF) antes y 30 min después de aplicar el parche Aeon. Indicador de balance autonómico.',
   results:['Aumento en potencia HF del VFC (p < 0.05)','Sugiere activación del sistema nervioso parasimpático','Sin efecto sobre FC media ni presión arterial'],
   pdf:'estudios/lifewave/aeon-heart-rate-variability.pdf',doi:'',note:''},
  {id:'lw-08',titulo_es:"Eficacia del parche Energy de LifeWave sobre la flexibilidad y la fuerza",temas:["mitocondria"],brand:'lifewave',type:'piloto',portada:'img/papers/energy-patches-flexibility-strength.jpg',
   title:'Efficacy of LifeWave Energy Patch on Flexibility and Strength',
   cite:'Tully L · Energy Medicine Research Institute · 2010',
   n:'N=30',loc:'EE.UU.',dur:'14 días',
   method:'Medición de flexibilidad (sit-and-reach), fuerza de agarre (dinamómetro) y resistencia (test de step) a los 0, 7 y 14 días.',
   results:['Mejoría del 20% en flexibilidad grupo activo vs 5% control','Aumento de fuerza de agarre documentado en la mayoría','Efectos desde las 24–48 horas de uso'],
   pdf:'estudios/lifewave/energy-patches-flexibility-strength.pdf',doi:'',note:''},
  {id:'lw-09',titulo_es:"Eficacia del parche de carnosina de LifeWave en flexibilidad, fuerza y resistencia",temas:["antioxidantes","mitocondria"],brand:'lifewave',type:'piloto',portada:'img/papers/carnosine-flexibility-strength.jpg',
   title:'Efficacy of LifeWave Carnosine Patch in Flexibility, Strength and Endurance',
   cite:'Tully L · Energy Medicine Research Institute · 2011',
   n:'N=30',loc:'EE.UU.',dur:'14 días',
   method:'Evaluación de flexibilidad, fuerza y resistencia en Día 0, 7 y 14. La carnosina actúa como buffer del pH muscular durante ejercicio intenso.',
   results:['Mejoría promedio del 23% en flexibilidad vs línea de base','Aumento de resistencia en test de caminata 6 min','Correlación con el rol buffer de la carnosina'],
   pdf:'estudios/lifewave/carnosine-flexibility-strength.pdf',doi:'',note:''},
  {id:'lw-10',titulo_es:"El parche SP6 Complete mejora la función de los órganos",temas:["microbioma"],brand:'lifewave',type:'piloto',portada:'img/papers/sp6-organ-function.jpg',
   title:'SP6 Complete Patch Improves Organ Function',
   cite:'Blake-Greenberg D, Nazeran H · 2009',
   n:'N=25',loc:'EE.UU.',dur:'4 semanas',
   method:'Evaluación de función hepática, renal y pancreática por análisis de sangre antes y después del parche SP6 Complete en punto de acupuntura SP6.',
   results:['Mejoría en parámetros de función hepática','Reducción de biomarcadores de inflamación sistémica','Resultados preliminares de regulación metabólica'],
   pdf:'estudios/lifewave/sp6-organ-function.pdf',doi:'',note:''},
  {id:'lw-11',titulo_es:"El parche no transdérmico ALAVIDA mejora el estado funcional celular",temas:["longevidad","antioxidantes"],brand:'lifewave',type:'piloto',portada:'img/papers/alavida-anti-aging.jpg',
   title:'ALAVIDA Non-transdermal Patch Improves Cellular Functional Status',
   cite:'LifeWave Research Division · 2015',
   n:'N=30 (40–65 años)',loc:'EE.UU.',dur:'60 días',
   method:'Evaluación de elasticidad cutánea (cutómetro), hidratación de piel y oxidación lipídica (MDA sérico) antes y después de 60 días de uso.',
   results:['Mejora del 18% en elasticidad de piel (cutómetro, p < 0.05)','Reducción de MDA sérico (oxidación lipídica)','Mejora subjetiva en apariencia y energía'],
   pdf:'estudios/lifewave/alavida-anti-aging.pdf',doi:'',note:''},
  {id:'lw-12',titulo_es:"Efecto de un parche de superficie no transdérmico sobre la función mitocondrial",temas:["mitocondria"],brand:'lifewave',type:'piloto',portada:'img/papers/mitochondrial-function-patch.jpg',
   title:'Non-Transdermal Surface Patch Effect on Mitochondrial Function',
   cite:'Shallenberger F, Nazeran H · —',
   n:'N=20',loc:'EE.UU.',dur:'4 semanas',
   method:'Medición de función mitocondrial por análisis de gas espiratorio (VO₂ máx y eficiencia metabólica) antes y después de la intervención.',
   results:['Mejora del 12% en eficiencia mitocondrial (VO₂/kg)','Correlación con reducción de fatiga subjetiva (FSS)','Sugiere activación de biogénesis mitocondrial'],
   pdf:'estudios/lifewave/mitochondrial-function-patch.pdf',doi:'',note:''},
  {id:'lw-13',titulo_es:"El efecto del GHK-Cu sobre la expresión génica relevante para la función del sistema nervioso y el deterioro cognitivo",temas:["longevidad","neuro"],brand:'lifewave',type:'revision',portada:'img/papers/ghk-gene-expression-brainsci-2017.jpg',
   title:'The Effect of GHK-Cu on Gene Expression Relevant to Nervous System Function and Cognitive Decline',
   cite:'Pickart L, Vasquez-Soltero JM, Margolina A · Brain Sciences · 2017',
   n:'>130 genes analizados',loc:'Revisión internacional',dur:'—',
   method:'Revisión en Brain Sciences del impacto del péptido GHK-Cu en >130 genes para el sistema nervioso. Análisis de microarray genómico (Affymetrix) y revisión de PubMed.',
   results:['GHK-Cu activa genes de regeneración nerviosa y neuroprotección (BDNF, NGF, VEGF)','Regula positivamente >54 genes de reparación del ADN y defensa antioxidante','Potencial en prevención del declive cognitivo y enfermedades neurodegenerativas'],
   pdf:'estudios/lifewave/ghk-gene-expression-brainsci-2017.pdf',doi:'10.3390/brainsci7020020',note:''},
  {id:'lw-14',titulo_es:"Mecanismos y aplicaciones de los efectos antiinflamatorios de la fotobiomodulación",temas:["luz","dolor"],brand:'lifewave',type:'revision',portada:'img/papers/hamblin-2017-pbm-anti-inflammatory-review.jpg',
   title:'Mechanisms and Applications of the Anti-Inflammatory Effects of Photobiomodulation',
   cite:'Hamblin MR · Harvard Medical School / MGH · AIMS Biophysics · 2017',
   n:'>150 estudios revisados',loc:'Harvard, Boston MA',dur:'—',
   method:'Análisis de mecanismos anti-inflamatorios de PBM/LLLT: vías NF-κB, citoquinas pro-inflamatorias, óxido nítrico, ROS y respuesta mitocondrial a luz roja/infrarroja cercana.',
   results:['PBM suprime TNF-α, IL-6 e IL-1β de forma consistente','Activa vías de supervivencia celular (Akt/PI3K), reduce apoptosis','Evidencia sólida en dolor crónico, recuperación músculo-esquelética y neuroprotección'],
   pdf:'estudios/lifewave/hamblin-2017-pbm-anti-inflammatory-review.pdf',doi:'10.3934/biophy.2017.3.337',note:'Hamblin: principal investigador mundial en fotobiomodulación.'},
  {id:'mvc-01',titulo_es:"La prolongación de la vida de ratas mediante la administración oral repetida de fulereno [60]",temas:["longevidad","antioxidantes"],brand:'myvitalc',type:'animal',portada:'img/papers/c60-olive-oil-lifespan-rats-2012.jpg',
   title:'The Prolongation of the Lifespan of Rats by Repeated Oral Administration of [60]Fullerene',
   cite:'Gharbi N, Szwarc M, Moussa M et al. · PLOS ONE · 2012',
   n:'N=6/grupo (Wistar)',loc:'CNRS, Túnez',dur:'Vida completa',
   method:'Ratas Wistar macho. Tres grupos: agua, aceite de oliva, C60 en aceite de oliva (1.7 mg/kg, 2x/semana). Evaluación de toxicidad hepática, estrés oxidativo y longevidad.',
   results:['C60 en aceite de oliva aumentó la vida útil ~90% vs control (p < 0.01)','Sin hepatotoxicidad ni toxicidad orgánica a largo plazo','C60 actúa como antioxidante catalítico — no se consume en la reacción'],
   pdf:'estudios/myvitalc/c60-olive-oil-lifespan-rats-2012.pdf',doi:'10.1371/journal.pone.0044481',note:'Paper seminal. Citado >500 veces. Mecanismos en humanos aún no confirmados en RCT.'},
  {id:'mvc-02',titulo_es:"Fulerenos en biología y medicina",temas:["antioxidantes","longevidad"],brand:'myvitalc',type:'revision',portada:'img/papers/c60-fullerenes-in-biology.jpg',
   title:'Fullerenes in Biology and Medicine',
   cite:'Edison-Castro A et al.',
   n:'Revisión bibliográfica',loc:'—',dur:'—',
   method:'Revisión de propiedades biológicas y médicas del C60. Análisis de capacidad antioxidante, biocompatibilidad y potencial en administración de fármacos y longevidad.',
   results:['C60 posee la mayor capacidad atrapadora de radicales libres conocida','Biocompatible a dosis terapéuticas en modelos animales','Potencial en neuroprotección, oncología y patologías de envejecimiento'],
   pdf:'estudios/myvitalc/c60-fullerenes-in-biology.pdf',doi:'',note:''},
  {id:'drh-01',titulo_es:"Hidrógeno molecular: un gas medicinal preventivo y terapéutico para diversas enfermedades",temas:["agua-h2","antioxidantes"],brand:'drinkhrw',type:'revision',portada:'img/papers/molecular-hydrogen-review-2017.jpg',
   title:'Molecular Hydrogen: A Preventive and Therapeutic Medical Gas for Various Diseases',
   cite:'Ge L, Yang M, Yang NN et al. · Oncotarget · 2017',
   n:'>321 artículos',loc:'Revisión internacional',dur:'—',
   method:'Revisión de 321 artículos sobre H₂ molecular en humanos y modelos animales. Clasificación por área: metabolismo, neurología, oncología, cardiovascular, deporte.',
   results:['H₂ demostró efectos en 321 enfermedades y condiciones documentadas','Antioxidante selectivo: neutraliza •OH y ONOO⁻ sin afectar ROS fisiológicas','Seguro y bien tolerado por agua enriquecida, inhalación o solución salina'],
   pdf:'estudios/drinkhrw/molecular-hydrogen-review-2017.pdf',doi:'10.18632/oncotarget.21130',note:''},
  {id:'drh-02',titulo_es:"Efectos del agua rica en hidrógeno sobre el rendimiento de resistencia muscular y la recuperación de la fatiga",temas:["agua-h2","mitocondria"],brand:'drinkhrw',type:'rct',portada:'img/papers/h2-muscular-endurance-2024.jpg',
   title:'Effects of Hydrogen-Rich Water on Muscular Endurance Performance and Fatigue Recovery',
   cite:'Zhou J et al. · Frontiers in Physiology · 2024',
   n:'N=30 atletas',loc:'China',dur:'4 semanas',
   method:'RCT doble ciego cruzado. Agua H₂ vs placebo (2 L/día). VO₂max, tiempo al agotamiento, CK, LDH, MDA, SOD antes y después.',
   results:['Reducción significativa de CK y LDH post-ejercicio (p < 0.05)','Mejora en tiempo al agotamiento en prueba incremental máxima','Mayor recuperación percibida y menor DOMS'],
   pdf:'estudios/drinkhrw/h2-muscular-endurance-2024.pdf',doi:'10.3389/fphys.2024.1458882',note:''},
  {id:'drh-03',titulo_es:"Efectos biológicos beneficiosos y mecanismos del hidrógeno molecular — 321 artículos originales",temas:["agua-h2","antioxidantes","neuro"],brand:'drinkhrw',type:'revision',portada:'img/papers/h2-neurological-protection-review-2015.jpg',
   title:'Beneficial Biological Effects and Underlying Mechanisms of Molecular Hydrogen — 321 Original Articles',
   cite:'Ichihara M, Sobue S, Ito M et al. · Medical Gas Research · 2015',
   n:'>321 estudios',loc:'U. Nagoya + U. Keio, Japón',dur:'—',
   method:'Revisión de todos los estudios en humanos, animales y células sobre H₂ hasta 2015. Mecanismos: activación Nrf2–ARE, reducción selectiva de ROS, anti-inflamatorio y anti-apoptótico.',
   results:['H₂ activa Nrf2–ARE regulando SOD, CAT y HO-1 endógenas','Efectos neuroprotectores en modelos de ACV, Parkinson y Alzheimer','Excelente perfil de seguridad en todos los estudios en humanos'],
   pdf:'estudios/drinkhrw/h2-neurological-protection-review-2015.pdf',doi:'10.1186/s13618-015-0035-1',note:''},
  {id:'drh-04',titulo_es:"Eficacia del agua rica en hidrógeno sobre el estado antioxidante en el síndrome metabólico potencial",temas:["agua-h2","antioxidantes","microbioma"],brand:'drinkhrw',type:'piloto',portada:'img/papers/h2-antioxidant-metabolic-jcbn-2010.jpg',
   title:'Effectiveness of Hydrogen Rich Water on Antioxidant Status in Potential Metabolic Syndrome',
   cite:'Nakao A, Inoue Y, Ookawara S et al. · J Clinical Biochemistry & Nutrition · 2010',
   n:'N=20',loc:'Japón',dur:'8 semanas',
   method:'Sujetos con síndrome metabólico potencial. 1.5–2 L agua H₂/día durante 8 semanas. Medición de 8-OHdG, isoprostanos, glucosa, lípidos y FRAP.',
   results:['Reducción significativa de 8-OHdG en orina (daño oxidativo al ADN, p < 0.05)','Mejora en capacidad antioxidante sérica total','Tendencia positiva en perfil lipídico y glucosa'],
   pdf:'estudios/drinkhrw/h2-antioxidant-metabolic-jcbn-2010.pdf',doi:'10.3164/jcbn.09-100',note:''},
  {id:'drh-05',titulo_es:"Efectos del agua rica en hidrógeno sobre las alteraciones de un modelo de síndrome metabólico en ratas SHR",temas:["agua-h2","microbioma"],brand:'drinkhrw',type:'animal',portada:'img/papers/h2-metabolic-shr-rat-mgr-2011.jpg',
   title:'Effects of Hydrogen-Rich Water on Abnormalities in a SHR Metabolic Syndrome Rat Model',
   cite:'Shirahata S, Hamasaki T, Teruya K · Medical Gas Research · 2011',
   n:'Ratas SHR obesas',loc:'Japón',dur:'Longitudinal',
   method:'Modelo animal de síndrome metabólico (rata SHR). Agua regular vs agua H₂ ad libitum. Peso, glucosa, perfil lipídico, presión arterial e histología hepática.',
   results:['Reducción de adiposidad visceral y peso en grupo H₂','Mejora en HOMA-IR y glucosa en ayunas','Reducción de ALT y AST (función hepática)'],
   pdf:'estudios/drinkhrw/h2-metabolic-shr-rat-mgr-2011.pdf',doi:'10.1186/2045-9912-1-26',note:''},
  {id:'drh-06',titulo_es:"Ensayo cruzado aleatorizado doble ciego controlado con placebo de agua enriquecida con H₂ para miopatías mitocondriales e inflamatorias",temas:["agua-h2","mitocondria"],brand:'drinkhrw',type:'rct',portada:'img/papers/h2-myopathy-crossover-rct-2011.jpg',
   title:'Randomized, Double-blind, Placebo-controlled Crossover Trial of H₂-enriched Water for Mitochondrial and Inflammatory Myopathies',
   cite:'Ito M, Ohno K, Ichihara M et al. · Medical Gas Research · 2011',
   n:'N=22 (5+17)',loc:'Hospital U. Keio, Tokio',dur:'Fase 1: 12 sem · Fase 2: cruzado',
   method:'Fase 1: ensayo abierto en miopatías mitocondriales. Fase 2: RCT doble ciego cruzado en miopatías inflamatorias. 0.5–1 L agua H₂/día. CK, lactato, fuerza muscular.',
   results:['Miopatías mitocondriales: reducción de lactato y mejora de fuerza','Miopatías inflamatorias: reducción de CK en período activo vs placebo (p = 0.008)','Primer RCT de H₂ en enfermedades neuromusculares'],
   pdf:'estudios/drinkhrw/h2-myopathy-crossover-rct-2011.pdf',doi:'10.1186/2045-9912-1-24',note:''},
  {id:'ana-01',titulo_es:"Efecto del agua Analemma sobre la producción mitocondrial de ATP: ensayo doble ciego controlado con placebo",temas:["agua-h2","mitocondria"],brand:'analemma',type:'rct',portada:'img/papers/analemma-atp-study-2022.jpg',
   title:'Effect of Analemma Water on Mitochondrial ATP Production: Double-blind Placebo-controlled Trial',
   cite:'Analemma Technologies · 2022',
   n:'N=38 adultos sanos',loc:'Europa Central',dur:'2 meses',
   method:'RCT doble ciego. Agua Analemma vs placebo. ATP intracelular por bioluminiscencia (luciferina-luciferasa) en células de sangre periférica antes y después de 2 meses.',
   results:['+20.3% producción de ATP intracelular en grupo Analemma (p < 0.01)','Grupo placebo sin cambio significativo','Correlación entre coherencia del agua (RMN) y producción energética'],
   pdf:'estudios/analemma/analemma-atp-study-2022.pdf',doi:'',note:'Estudio no publicado en revista indexada. Producido por el fabricante.'},
  {id:'ana-02',titulo_es:"Efecto del agua Analemma sobre la diversidad del microbioma intestinal: ensayo doble ciego controlado con placebo",temas:["agua-h2","microbioma"],brand:'analemma',type:'rct',portada:'img/papers/analemma-microbiome-study-2023.jpg',
   title:'Effect of Analemma Water on Gut Microbiome Diversity: Double-blind Placebo-controlled Trial',
   cite:'Analemma Technologies · 2023',
   n:'N=16 (disbiosis)',loc:'Europa Central',dur:'100 días',
   method:'Adultos con disbiosis diagnosticada. Agua Analemma vs placebo. Análisis microbioma 16S rRNA antes y después de 100 días.',
   results:['16% de mejora en índice de disbiosis (p < 0.05)','Aumento de diversidad microbiana (Shannon index)','Posible modulación del microbioma por estructura del agua'],
   pdf:'estudios/analemma/analemma-microbiome-study-2023.pdf',doi:'',note:'N pequeño (16 participantes). No publicado en revista peer-reviewed. Producido por fabricante.'},
  {id:'ana-03',titulo_es:"Zona de exclusión y estructura heterogénea del agua a temperatura ambiente",temas:["agua-h2"],brand:'analemma',type:'vitro',portada:'img/papers/pollack-ez-water-structure-2018.jpg',
   title:'Exclusion Zone and Heterogeneous Water Structure at Ambient Temperature',
   cite:'Mhanna R, Vaca Chavez F, Lahnsteiner A · PLOS ONE · 2018',
   n:'Experimentos in vitro',loc:'Múltiples laboratorios, Europa',dur:'—',
   method:'Investigación de la zona de exclusión (EZ water) con espectroscopía UV-Vis, microscopía óptica y difracción de neutrones. Estructura del agua en superficies hidrofílicas.',
   results:['Confirmación experimental de la cuarta fase del agua (EZ water)','La zona de exclusión excluye solutos y posee mayor densidad energética','Sustento científico para el concepto de agua estructurada en sistemas biológicos'],
   pdf:'estudios/analemma/pollack-ez-water-structure-2018.pdf',doi:'10.1371/journal.pone.0195057',note:'Publicado en PLOS ONE (peer-reviewed). Sustenta el concepto, no el producto específico.'},
  {id:'gam-01',titulo_es:"Seguridad, tolerabilidad y estimación de eficacia de la oscilación gamma evocada en la enfermedad de Alzheimer leve-moderada",temas:["neuro"],brand:'gamma',type:'rct',portada:'img/papers/hajos-2024-gamma-alzheimer-clinical-frontiers.jpg',
   title:"Safety, Tolerability, and Efficacy Estimate of Evoked Gamma Oscillation in Mild-Moderate Alzheimer's Disease",
   cite:'Hajos M, Moran SP, White P et al. · Frontiers in Neurology · 2024',
   n:'N=30 (AD leve-moderado)',loc:'EE.UU. (multicéntrico)',dur:'6 semanas',
   method:'RCT. Alzheimer leve-moderado (MMSE 14–26). Estimulación 40 Hz visual + auditiva sincronizada, 1 h/día. ADAS-Cog, MMSE y biomarcadores en LCR (Aβ₁₋₄₂, tau, p-tau).',
   results:['Mejora significativa en ADAS-Cog en grupo gamma vs control','Reducción de biomarcadores de Alzheimer en LCR (p < 0.05)','Sin efectos adversos graves; excelente tolerabilidad'],
   pdf:'estudios/gamma/hajos-2024-gamma-alzheimer-clinical-frontiers.pdf',doi:'10.3389/fneur.2024.1343588',note:''},
  {id:'gam-02',titulo_es:"Estimulación sensorial en frecuencia gamma en demencia de Alzheimer leve probable: estudio de factibilidad",temas:["neuro"],brand:'gamma',type:'factibilidad',portada:'img/papers/chan-2022-gamma-sensory-stimulation-alzheimer-plosone.jpg',
   title:"Gamma Frequency Sensory Stimulation in Mild Probable Alzheimer's Dementia: A Feasibility Study",
   cite:'Chan D, Freitas C, Ribeiro RL et al. · PLOS ONE · 2022',
   n:'N=13 (AD leve)',loc:'Portugal / EE.UU.',dur:'8 semanas',
   method:'Pacientes con AD leve (CDR 0.5–1). Estimulación 40 Hz, 1 h/día. Adherencia, tolerabilidad, EEG (64 canales) y MoCA.',
   results:['Adherencia del 91% al protocolo','Aumento de potencia gamma en EEG frontoparietal (p < 0.05)','Mantenimiento cognitivo vs declive esperado en controles históricos'],
   pdf:'estudios/gamma/chan-2022-gamma-sensory-stimulation-alzheimer-plosone.pdf',doi:'10.1371/journal.pone.0278412',note:''},
  {id:'gam-03',titulo_es:"Seguridad, tolerabilidad y eficacia preliminar de la estimulación sensorial de 40 Hz para la enfermedad de Alzheimer",temas:["neuro"],brand:'gamma',type:'seguridad',portada:'img/papers/agger-2023-gamma-safety-medrxiv.jpg',
   title:"Safety, Tolerability and Preliminary Efficacy of 40Hz Sensory Stimulation for Alzheimer's Disease",
   cite:'Agger M, Weiss U, Laursen B et al. · medRxiv · 2023',
   n:'N=13',loc:'Dinamarca',dur:'6 meses',
   method:'Estimulación sensorial 40 Hz, 1 h/día durante 6 meses. Registro sistemático de efectos adversos, QoL-AD y MMSE.',
   results:['Sin efectos adversos graves en 6 meses de uso diario','Estabilización de función cognitiva en la mayoría','MMSE estable vs declive esperado'],
   pdf:'estudios/gamma/agger-2023-gamma-safety-medrxiv.pdf',doi:'10.1101/2023.03.23.23287637',note:'Preprint — peer-review pendiente al momento de indexación.'},
  {id:'gam-04',titulo_es:"El parpadeo crónico de LED a 40 Hz no logró reducir la carga de amiloide en el modelo de ratón 5XFAD",temas:["neuro","luz"],brand:'gamma',type:'animal',portada:'img/papers/yang-2023-40hz-led-amyloid-eneuro.jpg',
   title:'Chronic 40Hz LED Flickering Failed to Reduce Amyloid Load in 5XFAD Mouse Model',
   cite:'Yang AC, Lai CK · eNeuro · 2023',
   n:'Ratones 5XFAD',loc:'Laboratorio',dur:'6 semanas',
   method:'Ratones 5XFAD (modelo transgénico severo de AD). LED 40 Hz vs luz constante vs oscuridad, 1 h/día. Inmunohistoquímica de placas amiloides y laberinto de Morris.',
   results:['No se observó reducción de placas amiloides en 5XFAD con 40 Hz LED','Contrasta con estudios MIT en modelos menos severos','El modelo 5XFAD puede ser demasiado severo para responder al tratamiento'],
   pdf:'estudios/gamma/yang-2023-40hz-led-amyloid-eneuro.pdf',doi:'10.1523/ENEURO.0189-23.2023',note:'Resultado negativo publicado en eNeuro. Relevante para contextualizar la evidencia.'},
  {id:'gam-05',titulo_es:"Avances en la investigación sobre la estimulación sensorial de 40 Hz para la enfermedad de Alzheimer — revisión",temas:["neuro"],brand:'gamma',type:'revision',portada:'img/papers/manippa-2025-40hz-sensory-stimulation-review-frontiers.jpg',
   title:"Research Progress on 40Hz Sensory Stimulation for Alzheimer's Disease — A Review",
   cite:'Manippa V, Moretta T, Taurisano P · Frontiers in Aging Neuroscience · 2025',
   n:'>80 estudios',loc:'Revisión internacional',dur:'—',
   method:'Revisión sistemática 2025 de todos los estudios sobre estimulación 40 Hz en Alzheimer. Mecanismos neurobiológicos, eficacia clínica y limitaciones metodológicas.',
   results:['Mecanismo: estimulación gamma activa microglía y promueve clearance de amiloide y tau','Evidencia clínica prometedora, aún limitada a estudios de N pequeño','Consenso: seguridad excelente, mecanismo sólido, se necesitan RCTs de mayor escala'],
   pdf:'estudios/gamma/manippa-2025-40hz-sensory-stimulation-review-frontiers.pdf',doi:'10.3389/fnagi.2025.1710041',note:''},
  {id:'gam-06',titulo_es:"Fotobiomodulación en modelos experimentales de la enfermedad de Alzheimer: estado del arte",temas:["luz","neuro"],brand:'gamma',type:'revision',portada:'img/papers/pbm-alzheimer-review-2024.jpg',
   title:"Photobiomodulation in Experimental Models of Alzheimer's Disease: State-of-the-Art",
   cite:"Hamblin MR, Liebert A et al. · Alzheimer's Research & Therapy · 2024",
   n:'>120 estudios',loc:'Harvard / Internacional',dur:'—',
   method:"Revisión en Alzheimer's Research & Therapy sobre PBM (luz infrarroja/roja) en modelos preclínicos y clínicos de AD. ATP mitocondrial, neuroinflamación, vías tau y amiloide.",
   results:['PBM mejora función cognitiva en modelos animales de AD de forma consistente','Primeros estudios en humanos: señales positivas en biomarcadores y cognición','Combinación PBM + gamma: sinergias terapéuticas en investigación activa'],
   pdf:'estudios/gamma/pbm-alzheimer-review-2024.pdf',doi:'10.1186/s13195-024-01484-x',note:''},
  {id:'gam-07',titulo_es:"Respuestas auditivas de estado estable a 40 Hz y procesamiento de información compleja",temas:["neuro"],brand:'gamma',type:'piloto',portada:'img/papers/gamma-40hz-auditory-ssep-plosone-2019.jpg',
   title:'40-Hz Auditory Steady-State Responses and Complex Information Processing',
   cite:'Dobrucky P, Kremen V, Laczo J et al. · PLOS ONE · 2019',
   n:'N=20 sanos (EEG)',loc:'Europa Central',dur:'Sesión única',
   method:'EEG de 64 canales en adultos sanos. Estimulación auditiva SSEP a 40 Hz. Correlaciones con batería cognitiva (N-back, memoria de trabajo).',
   results:['Estimulación 40 Hz genera oscilaciones gamma robustas en corteza auditiva y prefrontal','Correlación positiva con memoria de trabajo (r = 0.67)','Base electrofisiológica para uso terapéutico en humanos sanos'],
   pdf:'estudios/gamma/gamma-40hz-auditory-ssep-plosone-2019.pdf',doi:'10.1371/journal.pone.0223127',note:''},
  {id:'gam-08',titulo_es:"Efectos de los pulsos binaurales en frecuencia gamma sobre la atención y la ansiedad",temas:["neuro"],brand:'gamma',type:'rct',portada:'img/papers/gamma-binaural-beats-attention-anxiety-2023.jpg',
   title:'Effects of Gamma Frequency Binaural Beats on Attention and Anxiety',
   cite:'Kraus J, Porubanova M · Current Psychology · 2023',
   n:'N≈40',loc:'Europa Central',dur:'4 semanas',
   method:'Adultos con ansiedad leve-moderada. Binaural beats 40 Hz vs ruido blanco placebo, 20 min/día. CPT (atención sostenida), GAD-7, PANAS.',
   results:['Mejora en atención sostenida (CPT) grupo gamma (p < 0.05)','Reducción en GAD-7 vs placebo (p < 0.05)','Efectos mantenidos 2 semanas post-intervención'],
   pdf:'estudios/gamma/gamma-binaural-beats-attention-anxiety-2023.pdf',doi:'10.1007/s12144-023-04681-3',note:''},
  {id:'ng-01',titulo_es:"Cafeína y funciones cognitivas en el deporte: revisión sistemática y metaanálisis",temas:["neuro"],brand:'neurogum',type:'meta',portada:'img/papers/caffeine-sports-systematic-review-2021.jpg',
   title:'Caffeine and Cognitive Functions in Sports: A Systematic Review and Meta-analysis',
   cite:'Grgic J, Mikulic P, Schoenfeld BJ et al. · Nutrients · 2021',
   n:'>30 RCTs',loc:'Revisión internacional',dur:'—',
   method:'Meta-análisis de RCTs sobre cafeína y rendimiento cognitivo-físico en deportes. Análisis de dosis-respuesta y timing de administración.',
   results:['Cafeína mejora tiempo de reacción 3.5 ms (p < 0.001; IC 95%: −5.2 a −1.8)','Dosis óptima: 3–6 mg/kg, 45–60 min antes','Efecto robusto en resistencia y atención sostenida'],
   pdf:'estudios/neuro-gum/caffeine-sports-systematic-review-2021.pdf',doi:'10.3390/nu13030868',note:''},
  {id:'ng-02',titulo_es:"El efecto de la L-teanina sobre el rendimiento cognitivo: revisión sistemática y metaanálisis",temas:["neuro"],brand:'neurogum',type:'meta',portada:'img/papers/ltheanine-cognitive-meta-analysis-2025.jpg',
   title:'The Effect of L-Theanine on Cognitive Performance: A Systematic Review and Meta-analysis',
   cite:'Sashindran S, Mathew N, Ooi SL et al. · Journal of Clinical Medicine · 2025',
   n:'15 RCTs (meta-análisis)',loc:'Revisión internacional',dur:'—',
   method:'Meta-análisis de 15 RCTs sobre L-teanina sola y con cafeína. Atención, memoria de trabajo, velocidad de procesamiento y estado de ánimo. Evaluación GRADE.',
   results:['L-teanina + cafeína: efecto sinérgico en atención y velocidad de procesamiento (p < 0.01)','L-teanina sola: estado de alerta relajada sin sedación','NMD = 0.56 para atención sostenida (efecto mediano)'],
   pdf:'estudios/neuro-gum/ltheanine-cognitive-meta-analysis-2025.pdf',doi:'10.3390/jcm14217710',note:''},
  {id:'ng-03',titulo_es:"La L-teanina y la cafeína mejoran el cambio de tarea pero no la atención intersensorial",temas:["neuro"],brand:'neurogum',type:'rct',portada:'img/papers/einother-2010-ltheanine-caffeine-alertness.jpg',
   title:'L-theanine and Caffeine Improve Task Switching but Not Intersensory Attention',
   cite:'Einöther SJL, Martens VEG, Rycroft JA, De Bruin EA · Appetite · 2010',
   n:'N=27 voluntarios',loc:'Países Bajos (Unilever R&D)',dur:'Sesión única',
   method:'4 condiciones: L-teanina, cafeína, combinación, placebo. Batería cognitiva computerizada (Task Switching, RVIP, atención intersensorial). Diseño latino cuadrado.',
   results:['Combinación L-teanina+cafeína mejoró task switching vs placebo (p < 0.01)','Reducción de errores de comisión en cambio cognitivo','Beneficio selectivo sobre funciones ejecutivas'],
   pdf:'estudios/neuro-gum/einother-2010-ltheanine-caffeine-alertness.pdf',doi:'10.1016/j.appet.2010.01.003',note:''},
  {id:'ng-04',titulo_es:"Efectos de la cafeína y la L-teanina sobre el flujo sanguíneo cerebral, la cognición y el estado de ánimo",temas:["neuro"],brand:'neurogum',type:'rct',portada:'img/papers/dodd-2015-ltheanine-caffeine-cbf.jpg',
   title:'Effects of Caffeine and L-theanine on Cerebral Blood Flow, Cognition and Mood',
   cite:'Dodd FL, Kennedy DO, Riby LM, Haskell-Ramsay CF · Psychopharmacology · 2015',
   n:'N=24 voluntarios',loc:'Northumbria University, Reino Unido',dur:'Sesión única',
   method:'4 condiciones de dosis única. Flujo sanguíneo cerebral por NIRS (córtex prefrontal), batería COMPASS (atención, memoria) y Bond-Lader/PANAS.',
   results:['L-teanina incrementó flujo sanguíneo cerebral prefrontal izquierdo (p < 0.05)','Combinación mejoró atención sostenida y velocidad de procesamiento vs placebo (p < 0.01)','L-teanina sola: mayor calma sin sedación (Bond-Lader calm factor)'],
   pdf:'estudios/neuro-gum/dodd-2015-ltheanine-caffeine-cbf.pdf',doi:'10.1007/s00213-015-3895-0',note:''},
  {id:'ng-05',titulo_es:"Passiflora incarnata en los trastornos neuropsiquiátricos — revisión sistemática",temas:["neuro","sueno"],brand:'neurogum',type:'revision',portada:'img/papers/sarris-2020-passionflower-neuropsychiatric.jpg',
   title:'Passiflora incarnata in Neuropsychiatric Disorders — A Systematic Review',
   cite:'Sarris J, Byrne GJ, Cribb L et al. · Phytotherapy Research · 2020',
   n:'>20 estudios',loc:'U. Melbourne, Australia',dur:'—',
   method:'Revisión de estudios clínicos sobre Passiflora incarnata en ansiedad, insomnio y depresión. Fitoquímica (crisina, vitexina) y mecanismos GABA-érgicos.',
   results:['Eficacia comparable a oxazepam en ansiedad leve-moderada en 2 RCTs','Mejora de calidad del sueño en estudios con metodología rigurosa','Perfil de seguridad favorable; precaución con sedantes concomitantes'],
   pdf:'estudios/neuro-gum/sarris-2020-passionflower-neuropsychiatric.pdf',doi:'',note:''},
  {id:'ng-06',titulo_es:"Infusión de Passiflora incarnata sobre la calidad subjetiva del sueño — RCT doble ciego",temas:["sueno"],brand:'neurogum',type:'rct',portada:'img/papers/ngan-2011-passionflower-sleep-quality-rct.jpg',
   title:'Passiflora incarnata Herbal Tea on Subjective Sleep Quality — Double-blind RCT',
   cite:'Ngan A, Conduit R · Phytotherapy Research · 2011',
   n:'N=41',loc:'Melbourne, Australia',dur:'2 semanas (cruzado)',
   method:'Infusión de Passiflora o placebo 1 h antes de dormir. Diario de sueño estructurado, actigrafía y PSQI.',
   results:['Mejora significativa en PSQI global (p < 0.05 vs placebo)','Reducción del tiempo de latencia del sueño','Mayor sensación de haber dormido bien'],
   pdf:'estudios/neuro-gum/ngan-2011-passionflower-sleep-quality-rct.pdf',doi:'10.1002/ptr.3400',note:''},
  {id:'ng-07',titulo_es:"Efecto de la manzanilla oral sobre la calidad del sueño en adultos mayores — ensayo controlado aleatorizado",temas:["sueno"],brand:'neurogum',type:'rct',portada:'img/papers/chamomile-sleep-elderly-rct-2017.jpg',
   title:'Effect of Oral Chamomilla on Sleep Quality in Elderly People — Randomized Controlled Trial',
   cite:'Heidari Sh, Hashemzadeh M, Sharifzadeh G, Khodadadi A · J Education & Health Promotion · 2017',
   n:'N=60 (≥60 años)',loc:'Isfahan, Irán',dur:'4 semanas',
   method:'200 mg extracto de manzanilla 2x/día vs placebo. PSQI al inicio, 2 semanas y 4 semanas en adultos mayores con insomnio.',
   results:['Reducción PSQI: −4.2 puntos grupo manzanilla (p < 0.001) vs −0.3 placebo','Mejora en todas las subescalas del PSQI','Sin efectos adversos; buena tolerabilidad en población geriátrica'],
   pdf:'estudios/neuro-gum/chamomile-sleep-elderly-rct-2017.pdf',doi:'10.4103/jehp.jehp_109_15',note:''},
  {id:'ng-08',titulo_es:"Suplementación con GABA, variabilidad de la frecuencia cardíaca, eficiencia del sueño y depresión: RCT",temas:["sueno","neuro"],brand:'neurogum',type:'rct',portada:'img/papers/gaba-hrv-sleep-nutrients-2023.jpg',
   title:'GABA Supplementation, Heart-Rate Variability, Sleep Efficiency and Depression: RCT',
   cite:'Hepsomali P, Groeger JA, Nishihira J, Scholey A · Nutrients · 2023',
   n:'N=30',loc:'Japón / Europa',dur:'4 semanas (cruzado)',
   method:'100 mg GABA natural (PharmaGABA®) vs placebo. VFC por Holter 24 h, eficiencia del sueño por actigrafía, PHQ-9.',
   results:['GABA aumentó potencia HF del VFC (tono parasimpático, p < 0.05)','Mejora en eficiencia del sueño por actigrafía (p < 0.05)','Reducción de puntuación PHQ-9'],
   pdf:'estudios/neuro-gum/gaba-hrv-sleep-nutrients-2023.pdf',doi:'10.3390/nu15030695',note:''},
  {id:'ng-09',titulo_es:"Efecto de la suplementación con vitamina D sobre la depresión: revisión sistemática y metaanálisis",temas:["neuro"],brand:'neurogum',type:'meta',portada:'img/papers/liao-2023-vitaminD-depression-metaanalysis.jpg',
   title:'Effect of Vitamin D Supplementation on Depression: A Systematic Review and Meta-analysis',
   cite:'Liao MN, Ge XY, Zhang H et al. · Nutrients · 2023',
   n:'18 RCTs · N>4,000',loc:'China / Internacional',dur:'—',
   method:'Meta-análisis de 18 RCTs. Síntomas depresivos (HAMD, MADRS, BDI). Análisis de subgrupos por niveles basales de 25(OH)D y dosis.',
   results:['Vitamina D reduce síntomas depresivos vs placebo (SMD = −0.32; IC 95%: −0.52 a −0.13)','Mayor efecto con deficiencia basal de vitamina D (<20 ng/mL)','Dosis ≥ 2,000 UI/día con mayores beneficios antidepresivos'],
   pdf:'estudios/neuro-gum/liao-2023-vitaminD-depression-metaanalysis.pdf',doi:'10.3390/nu15040951',note:''},
  {id:'ng-10',titulo_es:"Suplementación con vitamina B sobre la cognición, la depresión y la ansiedad: revisión sistemática",temas:["neuro"],brand:'neurogum',type:'revision',portada:'img/papers/markun-2021-vitaminB-cognition-meta-analysis.jpg',
   title:'Vitamin B Supplementation on Cognition, Depression, and Anxiety: A Systematic Review',
   cite:'Markun S, Gravestock I, Jäger L et al. · Nutrients · 2021',
   n:'24 RCTs revisados',loc:'U. Zúrich, Suiza',dur:'—',
   method:'Meta-análisis de RCTs sobre vitaminas B6, B9 y B12 y resultados cognitivos, depresivos y de ansiedad. Evaluación Cochrane RoB y GRADE.',
   results:['Vitaminas B mejoran función cognitiva en adultos mayores con deficiencia','B9+B12 reducen homocisteína, factor de riesgo para declive cognitivo','Efecto consistente en ánimo en subgrupos con deficiencia de B12/folato'],
   pdf:'estudios/neuro-gum/markun-2021-vitaminB-cognition-meta-analysis.pdf',doi:'10.3390/nu13030923',note:''},

];
